services:
  # ðŸ§  Node Exporterï¼ˆä¸»æœºç›‘æŽ§ï¼‰
  node-exporter:
    image: prom/node-exporter:latest
    container_name: ne
    restart: unless-stopped
    ports:
      - "9100:9100"
    pid: "host"
    networks:
      - default
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    networks:
      - default
    volumes:
      - './db_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    entrypoint: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD} --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "6379"
    networks:
      - default
    volumes:
      - './redis_data:/data'
      - '/etc/timezone:/etc/timezone:ro'

  wordpress:
    depends_on:
      - mysql
      - redis
    image: wordpress:latest
    container_name: wp
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST','redis');
        define('WP_REDIS_PORT','6379');
        define('WP_REDIS_PASSWORD','${REDIS_PASSWORD}');
        define('WP_CACHE_KEY_SALT','${WP_CACHE_KEY_SALT}');
        define('WP_CACHE',true);
        
      REDIS_HOST: redis
    volumes:
      - './wp_content:/var/www/html/wp-content'
      #- './custom-plugins:/var/www/html/wp-content/plugins'


networks:
  default:
    name: wordpress
